plugins {
    id 'java-library'
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
    implementation("io.github.sandydunlop:markista:0.1.19")
}

java {
    withJavadocJar()
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

