package io.github.sandydunlop.markista.docservice.docagrams.structure;

import java.io.IOException;
import java.io.Writer;
import java.util.List;

import io.github.sandydunlop.markista.core.Context;

public class TreeSvgWriter {
    /// The Writer used to output the generated markdown content for the current document.
    /// It handles writing text to the appropriate output file or stream.
    private Writer writer;

    TreeNode root;
    List<TreeNode> contents;
    AbstractTree tree;

    /// The Context singleton instance providing access to the current documentation generation context,
    /// including configuration, current module/package/type names, and reporting utilities.
    /// > **Warning**<br/>
    /// Do not make this `final`. It will break tests with mocked [Context].
    private Context ctx;

    public TreeSvgWriter() {
        this.ctx = Context.getInstance();
    }

    public void setContext(Context context) {
        ctx = context;
    }

    public void setContents(List<TreeNode> contents) {
        this.contents = contents;
    }

    public void write(AbstractTree tree, String fileName) throws IOException {
        this.tree = tree;
        this.contents = tree.getContents();
        this.root = tree.getRoot();
        ctx.setModuleName(tree.getModuleName());
        writer = ctx.createFileInModule("diagrams/" + fileName);
        writer.write(top());
        writeContents(contents);
        writer.write(bot());
        writer.flush();
        writer.close();
    }

    public void writeContents(List<TreeNode> contents) throws IOException {
        for (TreeNode treeNode : contents) {
            writeEntry(treeNode);
        }
    }

    private void writeEntry(TreeNode treeNode) throws IOException{
        Icon icon = treeNode.getIcon();
        String label = treeNode.getLabel();
        String name = "module_" + escapeName(treeNode.getLabel());
        writer.write("  <g data-cell-id=\"" + name + "\">\n");
        writer.write("    <g data-cell-id=\"" + name + "_icon\">\n");
        writer.write(icon.placeAt(treeNode.getX(), treeNode.getY()));
        writer.write("    </g>\n");
        writer.write("    <g data-cell-id=\"" + name + "_label\">\n");
        writer.write(String.format("      <text x=\"%d\" y=\"%d\" fill=\"light-dark(#505050, #B9B5B4)\" font-family=\"Helvetica\" font-size=\"12px\">%s</text>\n", treeNode.getX() + 18, treeNode.getY() + 10, label));
        writer.write("    </g>\n");

        if (treeNode.getParent() != null) {
            writeLines1(treeNode);
        }

        writer.write("  </g>\n");
    }

    private void writeLines1(TreeNode treeNode) throws IOException {
        writer.write("    <g>\n");
        //#726C70
        writer.write(String.format("      <path d=\"M %d %d L %d %d\" fill=\"none\" stroke=\"#505050\" stroke-miterlimit=\"10\" pointer-events=\"stroke\" style=\"stroke: light-dark(#505050, #726C70);\"/>\n",
                treeNode.getParent().getX() + 7, treeNode.getY(), treeNode.getParent().getX() + 7, treeNode.getParent().getY() + 14));

                writer.write(String.format("      <path d=\"M %d %d Q %d %d %d %d\" fill=\"none\" stroke=\"#505050\" stroke-miterlimit=\"10\" pointer-events=\"stroke\" style=\"stroke: light-dark(#505050, #726C70);\"/>\n",
                treeNode.getParent().getX() + 7, treeNode.getY(),  treeNode.getParent().getX() + 7,   treeNode.getY() + 6     , treeNode.getX() - 5, treeNode.getY() + 6));

                writer.write(String.format("      <path d=\"M %d %d L %d %d\" fill=\"none\" stroke=\"#505050\" stroke-miterlimit=\"10\" pointer-events=\"stroke\" style=\"stroke: light-dark(#505050, #726C70);\"/>\n",
                treeNode.getX() - 5, treeNode.getY() + 6, treeNode.getX() - 2, treeNode.getY() + 6));
        writer.write("    </g>\n");
    }

    private String escapeName(String name) {
        return name.replace(".", "_");
    }

    private String top() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + //
                        "<!-- Do not edit this file with editors other than draw.io -->\n" + //
                        "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n" + //
                        "<svg\n" + //
                        "\txmlns=\"http://www.w3.org/2000/svg\" style=\"background: transparent; background-color: transparent; color-scheme: light dark;\"\n" + //

                        // String.format("\txmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" width=\"%dpx\" height=\"%dpx\" viewBox=\"0 0  %d %d\" content=\"\">\n",
                        //         tree.getWidth(), tree.getHeight(), tree.getWidth(), tree.getHeight()) + //

                        String.format("\txmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" height=\"%dpx\">\n",
                                tree.getHeight()) + //

                        "\t<defs/>\n" + //
                        "\t<g>\n" + //
                        "\t\t<g data-cell-id=\"0\">\n" + //
                        "\t\t\t<g data-cell-id=\"1\">";        
    }

    private String bot() {
        return "\t\t\t</g>\n" + //
                        "\t\t</g>\n" + //
                        "\t</g>\n" + //
                        "</svg>\n";
    }
}
